[relaychain]
default_image = "docker.io/paritypr/polkadot-debug:master"
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]


chain = "kusama-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  ws_port = 9984
  rpc_port = 9985
  prometheus_port = 9986

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  ws_port = 9994
  rpc_port = 9995
  prometheus_port = 9996