name: 'Hello World'
description: 'Greet someone'
runs:
  using: 'composite'
  steps:
    - name: podman
      run: sudo apt-get -y update
    - name: podman install
      run: sudo apt-get -y install podman
    - name: Run zombienet
      run: npm run zombienet:podman
