name: Continuous Integration

on: [push, pull_request, workflow_dispatch]

jobs:
  ci:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[CI Skip]')"
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install
        run: yarn install --check-files

      - name: Format
        run: yarn format:check

      - name: Lint
        run: yarn lint:check

      - name: Audit
        run: yarn audit

      - name: Build
        run: yarn build
