# Continuously tests the development env
name: Continuous Testing

on:
  workflow_dispatch:
#  schedule:
    # * is a special character in YAML so you have to quote this string
#    - cron:  '0 0 * * *' # Every day at midnight

jobs:
  tests:
    timeout-minutes: 10
    name: 'E2E Tests - ${{ matrix.project }} - Shard ${{ matrix.shardIndex }} of ${{ matrix.shardTotal }}'
    runs-on: ubuntu-latest
    environment: github-pages
    container:
      image: mcr.microsoft.com/playwright:v1.35.1-focal
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
        working-directory: test
      - name: Run tests
        run: npx playwright test
        working-directory: test
        env:
          # TODO extract this URL from context
          URL: https://paritytech.github.io/governance-ui
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
