name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      # Spawn a zomboienet chain in background
      # ToDo: switch to zombienet podman when static ports are supported
      # podman is preferred but currently it is not possible to set static ports
      #- name: podman
      #  run: sudo apt-get -y update
      # zombinet
      #- name: podman install
      #  run: sudo apt-get -y install podman
      #- name: Run zombienet
      #  run: yarn zombienet:podman
      - name: download polkadot
        run: |
          curl -L https://github.com/paritytech/polkadot/releases/download/v0.9.37/polkadot -o "${GITHUB_WORKSPACE}/polkadot"
          chmod 777 "${GITHUB_WORKSPACE}/polkadot"
          echo PATH=$PATH:"${GITHUB_WORKSPACE}" >> $GITHUB_ENV
      - name: check polkadot
        run: polkadot --version

      - name: Background Zombienet Server
        uses: BerniWittmann/background-server-action@v1
        with:
          start: yarn zombienet:native
          wait-on: "http://127.0.0.1:9996/metrics"

      # Start the web app in background
      - name: Background App Server
        uses: BerniWittmann/background-server-action@v1
        with:
          start: yarn dev
          wait-on: "http://localhost:1234"

      # tests
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: Run Playwright tests
        run: yarn playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
